name: Telegram Notify
inputs:
  to:
    description: 'telegram group/channel/user id'
    required: false
    default: ''
  token:
    description: 'telegram bot token'
    required: false
    default: ''
  message:
    description: 'telegram message'
    required: false
    default: 'blank'
  format:
    description: 'message format: markdown or html'
    required: false
    default: 'markdown'
  map_users:
    description: 'Map of github:telegram users in quote/double quote '
    required: false    
  user:
    description: 'Github User want to tag in Telegram'
    required: false
outputs:
  reviewer:
    description: 'Tagged Telegram user'
    value: ${{ join(steps.map-user.outputs.*, ', ') }}
runs:
  using: "composite"
  steps:    
    - id: map-user
      if: ${{ inputs.map_users }}
      run: | 
        #echo "${{ join(fromjson(inputs.user), ' ') }}"
        for user in ${{ join(fromjson(inputs.user), ' ') }} 
        do
          echo "${{ $(echo "$user") }}"
        done
      shell: bash
    - id: send-message
      if: ${{ inputs.token }}
      run: |
        curl  --silent --output /dev/null --show-error --fail \
              -X POST 'https://api.telegram.org/bot${{ inputs.token }}/sendMessage' \
              -H 'Content-Type: application/json' \
              -d '{ "chat_id": "${{ inputs.to }}", 
                    "parse_mode": "${{ inputs.format }}", 
                    "text": "${{ inputs.message }}" 
                  }'
      shell: bash
